# start by pulling the python image
FROM python:3.9

ENV FLASK_APP search_app
ENV FLASK_ENV development

# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt
COPY ./static /app/static
COPY ./templates /app/templates
COPY ./utils /app/utils
COPY ./search_app.py /app/search_app.py
COPY ./test_app.py /app/test_app.py

# install the dependencies and packages in the requirements file
RUN pip3 install -r /app/requirements.txt

# switch working directory
WORKDIR /app

# configure the container to run in an executed manner
ENTRYPOINT [ "/bin/bash" ]

CMD [ "flask run -p 8080 -h '0.0.0.0'" ]